### ISSUE TITLE
`transforms.ConvertImageDtype` is not necessary.

### ISSUE THREAD

**Issue by seonho** [kairos03/pytorch-scriptable-transforms-tutorial#1]
안녕하세요.

우선, 좋은 글 감사합니다.

알고계실 수도 있지만, 입력이 torch.ByteTensor로 표현될 수 있는 경우(24 bit RGB)에는 `transforms.ToTensor`에서 자동으로 `float`로 변환됩니다.
그래서 `transforms.ConvertImageDtype`를 사용하지 않으셔도 됩니다.

Reference:
- https://github.com/pytorch/vision/blob/a3c0e67cca876185092de20cd71cf8b67e474939/torchvision/transforms/functional.py#L89

**Comment by kairos03** [comment]
네, 코멘트 감사합니다. 저도 빼보고 하긴했었는데 공식 튜토리얼을 들고오다 보니 코멘트 적는걸 깜빡했네요 감사합니다.
